[project]
name = "GNN_Ranking"
version = "0.1.0"
description = ""
authors = [
    {name = "Pierrot LC", email = "pierrotlc@proton.me"},
]
dependencies = []
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}
